const theme = {
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 20,
  PRIMARY_COLOR: '#79a3b1',
  SECONDARY_COLOR: '#fcf8ec',
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
};
export {theme};
